#!/bin/sh

PARALLEL=`which parallel`
if [ -z $PARALLEL ]
then
  echo "Needs GNU parallel"
  exit 1
fi

# This finds the location where chic itself is stored
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

cp "$DIR/Garamond Regular.ttf" .

# number of files
count=$(ls *.jpg | wc -l)
# name of a file
first=$(ls *.jpg | head -n1 | sed 's/-[0-9]*.jpg//')

read -p "Title: "
title=$REPLY
read -p "Date: "
date=$REPLY

cat >> index.html << HEREDOC
<html>
<meta charset=utf-8>
<head>
<title>
</title>
<style>
 @font-face {
  font-family: a;
  src: url("Garamond Regular.ttf");
 }
  body, html {
    margin: 0;
    padding: 0;
    background-color: #050000;
    color: #ccc;
    font-family: "a";
  }
  .wrapper {
    box-sizing: border-box;
    padding: 0;
    margin: 0;
    display: flex;
    align-items: center;
    flex-direction: column;
    justify-content: space-between;
    width: 95vw;
    margin: 0 auto;
  }
  img {
    display: block;
    max-width: 90vw;
    max-height: 90vh;
    margin-bottom: 50vh;
    border: 1em solid white;
  }
  @media screen and (orientation:portrait) { 
    span {
      font-size: 13vw;
    }
  }
  @media screen and (orientation:landscape) { 
    span {
      font-size: 13vh;
    }
  }
  span {
    display: block;
    text-align: left;
    animation-name: opacity;
    animation-duration: 1s;
    animation-iteration-count: 1;
    animation-fill-mode: both;
  }
  #title {
    height: 100vh;
    width: 90vw;
    padding-left: 1vw;
    padding-top: 30vh;
    font-size: 30vh;
    text-align: center;
  }
  #date {
    padding-right: 1vw;
    text-align: right;
    height: 50vh;
    width: 90vw;
    font-size: 5vh;
  }
  #zip {
    padding-right: 1vw;
    text-align: right;
    height: 10vh;
    width: 90vw;
    font-size: 5vh;
    text-decoration: none;
  }
  a {
    color: #cdd;
  }
  #zip:visited {
    color: white;
  }
</style>
</head>
<body>
<div class=wrapper>
  <div id=title>
  $title
  </div>
  <div id=date>
  $date
  </div>
HEREDOC


for i in $(seq -f "%05g" 1 $count)
do
  echo "<img srcset=\"$first-$i.jpg 2000w, \
$first-$i-half.jpg 1500w, \
$first-$i-quarter.jpg 600w\" sizes=\"(max-width: 600px) \
600px, (max-width: 1500px) 1500px, 2000px\" \
src=\"$first-$i.jpg\">" >> index.html
done

echo "<a id=zip href=\"$first.zip\">zip</a>" >> index.html
echo "</div>" >> index.html
echo "</body>" >> index.html
echo "</html>" >> index.html

mkdir "$title"
mv *.jpg "$title"
zip "$title".zip  "$title"/*
mv "$title"/*.jpg .
rmdir "$title"

find . -name "*.jpg" -type f | parallel --eta convert -resize 50% {} {.}-half.jpg
find . -name "*-half.jpg" -type f | parallel --eta convert -resize 50% {} {.}-quarter.jpg
rename "s/half-quarter/quarter/" *.jpg

open index.html
